IMAGE_NAME = "bento/ubuntu-18.04"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
    config.vm.define "ElaRedis" do |master|
		master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "172.28.128.8"
        master.vm.hostname = "ElaRedis"
		master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "ansible-playbook/elaredis-playbook.yml"
            ansible.extra_vars = {
                node_ip: "172.28.128.9",
            }
         end
  
     end
end